### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Novanox4** [TeamOct/fictional-octo-system#27] opened 2024-06-15 14:05 UTC
I went to the first sector of the game and after a few seconds it crashed

Crash log:

Mindustry has crashed. How unfortunate.
Version: bleeding-edge build 25059
OS: Linux xnull (aarch64)
Android API level: 30
Java Version: 0
Runtime Available Memory: 192mb
Cores: 8
Mods: auto-research:Algorithm 1.2, biotech:0.2, bl-ui-lib:7, fos:1.1 beta build-2.2, fosost:1.0.3, mapfilterext:1.7.6b, mapping-utilities:1.7, mindustry-mapping-utilities:0.15, mitour-lib:0.2.1, mobile-mapshot:1.0.0, multi-crafter:1.8, newconsole:1.9, scheme-size:2.7.79, test-utils:65, time-control:0.2

> AbstractMethodError: 'abstract method "int mindustry.gen.Unitc.collisionLayer()"'
PhysicsProcess.begin: 17
AsyncCore.begin: 3
ClientLauncher.update: 21
AndroidGraphics.onDrawFrame: 22
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286

**Comment by Slotterleet** [comment] 2024-06-15 14:07
Duplicate of #25 - FOS is unsupported in Bleeding Edge versions of the game.

**Closed as not planned by Slotterleet** 2024-06-15 14:07 UTC
